import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-vercel-postgres'

// Generated by `payload migrate:create`, then hand-edited: localizing a field moves it to a
// `_locales` table, and the generated SQL dropped `media.alt` without carrying the 141 existing
// strings across. The two INSERT/UPDATE steps below are the whole point of this file — without
// them the migration is a delete.
export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
  CREATE TABLE "media_locales" (
  	"alt" varchar NOT NULL,
  	"id" serial PRIMARY KEY NOT NULL,
  	"_locale" "_locales" NOT NULL,
  	"_parent_id" integer NOT NULL
  );

  ALTER TABLE "media_locales" ADD CONSTRAINT "media_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."media"("id") ON DELETE cascade ON UPDATE no action;
  CREATE UNIQUE INDEX "media_locales_locale_parent_id_unique" ON "media_locales" USING btree ("_locale","_parent_id");

  INSERT INTO "media_locales" ("alt", "_locale", "_parent_id")
  SELECT "alt", 'pl'::"_locales", "id" FROM "media";

  ALTER TABLE "media" DROP COLUMN "alt";`)
}

// The English rows this leaves behind are dropped with the table — going back means the site
// has one alt string per photo again, so there is nowhere to put them.
export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
  ALTER TABLE "media" ADD COLUMN "alt" varchar;

  UPDATE "media" SET "alt" = "media_locales"."alt"
  FROM "media_locales"
  WHERE "media_locales"."_parent_id" = "media"."id" AND "media_locales"."_locale" = 'pl';

  ALTER TABLE "media" ALTER COLUMN "alt" SET NOT NULL;

  DROP TABLE "media_locales" CASCADE;`)
}
